const fs = require('fs');

const rawData = {
  grades: [
    { id: "1A", name: "一上" },
    { id: "1B", name: "一下" },
    { id: "2A", name: "二上" },
    { id: "2B", name: "二下" }
  ],
  components: [
    { id: "woman", symbol: "女", name: "女子之閣", meaning: "與女性、親屬有關", color: "#f472b6", theme: "pink-garden" },
    { id: "hand", symbol: "手", name: "工匠之坊", meaning: "與手部動作有關", color: "#fb923c", theme: "workshop" },
    { id: "person", symbol: "人", name: "英雄聖域", meaning: "與人類行為有關", color: "#a855f7", theme: "sky-temple" },
    { id: "mouth", symbol: "口", name: "言之靈壇", meaning: "與嘴巴動作有關", color: "#ef4444", theme: "echo-cave" },
    { id: "water", symbol: "水", name: "水之神殿", meaning: "與液體、流動有關", color: "#3b82f6", theme: "ocean-bubbles" },
    { id: "wood", symbol: "木", name: "木之森林", meaning: "與樹木、植物有關", color: "#10b981", theme: "forest-leaves" },
    { id: "foot", symbol: "足", name: "征途之徑", meaning: "與腳部動作有關", color: "#78350f", theme: "earth-trail" },
    { id: "heart", symbol: "心", name: "心靈之閣", meaning: "與情感、思考有關", color: "#ec4899", theme: "love-cloud" },
    { id: "speech", symbol: "言", name: "真言之塔", meaning: "與語言、記錄有關", color: "#6366f1", theme: "magic-library" },
    { id: "grass", symbol: "艸", name: "草本奇境", meaning: "與草本、花卉有關", color: "#22c55e", theme: "wildflower" },
    { id: "silk", symbol: "糸", name: "絲綢之路", meaning: "與細線、編織有關", color: "#d946ef", theme: "loom-palace" },
    { id: "insect", symbol: "虫", name: "蟲鳴之里", meaning: "與昆蟲、節肢動物有關", color: "#84cc16", theme: "bug-meadow" },
    { id: "sun", symbol: "日", name: "時光神殿", meaning: "與光影、時間有關", color: "#eab308", theme: "solar-temple" },
    { id: "gate", symbol: "門", name: "禁忌之門", meaning: "與出入口、封閉有關", color: "#64748b", theme: "iron-gate" },
    { id: "rain", symbol: "雨", name: "雨幕之廊", meaning: "與氣候、水氣有關", color: "#0ea5e9", theme: "rain-mist" },
    { id: "bird", symbol: "鳥", name: "蒼穹之巢", meaning: "與鳥類、飛翔有關", color: "#94a3b8", theme: "sky-nest" },
    { id: "extra", symbol: "➕", name: "傳說補充", meaning: "其他有趣的文字", color: "#334155", theme: "star-void" }
  ],
  characters: {
    // 1. 女部 (9 個)
    "好": { grade: "1A", zhuyin: "ㄏㄠˇ", comp: "woman", definition: "優良；喜愛。", phrases: ["友好", "好聽"], sentence: "這本書很好看。", breakdown: ["女", "子"], logic: "媽媽帶孩子。", story: "媽媽帶著心愛的孩子，是一件非常美好的事。" },
    "媽": { grade: "1B", zhuyin: "ㄇㄚ", comp: "woman", definition: "母親。", phrases: ["媽媽"], sentence: "媽媽煮飯真好吃。", breakdown: ["女", "馬"], logic: "女性家庭成員。", story: "媽媽像馬一樣勤奮地照顧全家人。" },
    "姐": { grade: "1B", zhuyin: "ㄐㄧㄝˇ", comp: "woman", definition: "姊姊。", phrases: ["姊姊"], sentence: "姊姊喜歡唱歌。", breakdown: ["女", "且"], logic: "年長女性成員。", story: "比我年紀大的女性同輩就是姊姊。" },
    "妹": { grade: "1B", zhuyin: "ㄇㄟˋ", comp: "woman", definition: "妹妹。", phrases: ["妹妹"], sentence: "妹妹在玩洋娃娃。", breakdown: ["女", "未"], logic: "未長大的女孩。", story: "家中年紀最小的女生是我的妹妹。" },
    "她": { grade: "1B", zhuyin: "ㄊㄚ", comp: "woman", definition: "女生他。", phrases: ["她們"], sentence: "她是我的好朋友。", breakdown: ["女", "也"], logic: "指女性的代名詞。", story: "當我們指著那個女生說話，就用這個代名詞。" },
    "奶": { grade: "2A", zhuyin: "ㄋㄞˇ", comp: "woman", definition: "奶奶。", phrases: ["奶奶"], sentence: "奶奶每天去散步。", breakdown: ["女", "乃"], logic: "養育後代的長輩。", story: "奶奶是爸爸的媽媽，她最疼愛我了。" },
    "妙": { grade: "2B", zhuyin: "ㄇㄧㄠˋ", comp: "woman", definition: "奇特；美好。", phrases: ["美妙"], sentence: "天空的雲真美妙。", breakdown: ["女", "少"], logic: "少女姿態優美。", story: "這件事情發生得太奇特了，真神奇！" },
    "姑": { grade: "2B", zhuyin: "ㄍㄨ", comp: "woman", definition: "父親的姊妹。", phrases: ["姑姑"], sentence: "姑姑來我家玩。", breakdown: ["女", "古"], logic: "父系女性長輩。", story: "爸爸的姊姊或妹妹，我們喊她姑姑。" },
    "娘": { grade: "2B", zhuyin: "ㄋㄧㄤˊ", comp: "woman", definition: "稱呼女性。", phrases: ["姑娘"], sentence: "路邊有一位姑娘。", breakdown: ["女", "良"], logic: "優質的女性。", story: "古代稱呼年輕的女生為姑娘。" },

    // 2. 手部 (26 個)
    "手": { grade: "1B", zhuyin: "ㄕㄡˇ", comp: "hand", definition: "人體的上肢。", phrases: ["雙手"], sentence: "洗手保健康。", breakdown: ["手"], logic: "象形字，像人的手指。", story: "萬能的雙手可以幫我們拿東西和畫畫。" },
    "招": { grade: "1B", zhuyin: "ㄓㄠ", comp: "hand", definition: "揮手引人。", phrases: ["招手"], sentence: "老師對我們招手。", breakdown: ["扌", "召"], logic: "用手呼喚人來。", story: "朋友在對我招手，叫我過去一塊玩。" },
    "找": { grade: "1B", zhuyin: "ㄓㄠˇ", comp: "hand", definition: "尋求。", phrases: ["尋找"], sentence: "我在找我的筆。", breakdown: ["扌", "戈"], logic: "拿著工具動手找。", story: "玩具不見了，我正在房間裡仔細找。" },
    "拍": { grade: "1B", zhuyin: "ㄆㄞ", comp: "hand", definition: "掌擊。", phrases: ["拍手"], sentence: "大家一起來拍手。", breakdown: ["扌", "白"], logic: "手掌露出白掌心。", story: "聽到好聽的音樂，我們跟著拍拍手。" },
    "拿": { grade: "1B", zhuyin: "ㄋㄚˊ", comp: "hand", definition: "手握取物。", phrases: ["拿走"], sentence: "請幫我拿那本書。", breakdown: ["合", "手"], logic: "雙手合力拿東西。", story: "我用兩隻手，把重重的箱子拿起來。" },
    "幫": { grade: "1B", zhuyin: "ㄅㄤ", comp: "hand", definition: "協助。", phrases: ["幫忙"], sentence: "我幫媽媽掃地。", breakdown: ["邦", "巾"], logic: "提供協助。", story: "同學遇到困難，我要主動伸手幫忙。" },
    "拉": { grade: "1B", zhuyin: "ㄌㄚ", comp: "hand", definition: "牽引。", phrases: ["拉開"], sentence: "我把門拉開了。", breakdown: ["扌", "立"], logic: "動手讓物立起。", story: "我和弟弟在玩拉小車的遊戲。" },
    "推": { grade: "1B", zhuyin: "ㄊㄨㄟ", comp: "hand", definition: "向外移。", phrases: ["推開"], sentence: "請用力推開大門。", breakdown: ["扌", "隹"], logic: "手推著鳥前進。", story: "牆壁推不動，但這台小車可以推著走。" },
    "把": { grade: "1B", zhuyin: "ㄅㄚˇ", comp: "hand", definition: "握住；量詞。", phrases: ["一把"], sentence: "我有一把泥土。", breakdown: ["扌", "巴"], logic: "緊緊握在手裡。", story: "我把門把緊緊握住用力一轉，門就開了。" },
    "抓": { grade: "2A", zhuyin: "ㄓㄨㄚ", comp: "hand", definition: "指尖用力。", phrases: ["抓緊"], sentence: "小貓抓住了球。", breakdown: ["扌", "爪"], logic: "手像鳥爪抓物。", story: "玩捉迷藏時，我要趕快抓到大家。" },
    "搶": { grade: "2A", zhuyin: "ㄑㄧㄤˇ", comp: "hand", definition: "爭奪。", phrases: ["爭搶"], sentence: "不要搶別人的書。", breakdown: ["扌", "倉"], logic: "手伸向穀倉奪取。", story: "大家排好隊，不要在公車前爭搶。" },
    "接": { grade: "2A", zhuyin: "ㄐㄧㄝ", comp: "hand", definition: "迎接。", phrases: ["接受"], sentence: "他接住了球。", breakdown: ["扌", "妾"], logic: "伸出手去迎接。", story: "球飛過來了，我伸出雙手接住。" },
    "搖": { grade: "2A", zhuyin: "ㄧㄠˊ", comp: "hand", definition: "擺動。", phrases: ["搖頭"], sentence: "樹葉在微風搖。", breakdown: ["扌", "傜"], logic: "手拿物體擺盪。", story: "弟弟一邊聽音樂，一邊搖著身體。" },
    "撥": { grade: "2A", zhuyin: "ㄅㄛ", comp: "hand", definition: "推向一邊。", phrases: ["撥開"], sentence: "請撥開草叢看。", breakdown: ["扌", "發"], logic: "手像箭發射般推。", story: "我把雜物撥到旁邊，清出空間。" },
    "指": { grade: "2A", zhuyin: "ㄓˇ", comp: "hand", definition: "手指；向。", phrases: ["指向"], sentence: "他指著遠方的山。", breakdown: ["扌", "旨"], logic: "手指出目標。", story: "老師指著黑板上的字，教我們讀書。" },
    "甩": { grade: "2B", zhuyin: "ㄕㄨㄞˇ", comp: "hand", definition: "揮動使離。", phrases: ["甩開"], sentence: "他用力甩掉水。", breakdown: ["爪", "用"], logic: "用手勁讓物脫離。", story: "洗完手後，我輕輕甩掉手上的水。" },
    "提": { grade: "2B", zhuyin: "ㄊㄧˊ", comp: "hand", definition: "懸空拿著。", phrases: ["提燈"], sentence: "爸爸提著行李箱。", breakdown: ["扌", "是"], logic: "手把東西拎正。", story: "我幫外婆提籃子去市場買菜。" },
    "擔": { grade: "2B", zhuyin: "ㄉㄢ", comp: "hand", definition: "擔負。", phrases: ["負擔"], sentence: "我們要承擔責任。", breakdown: ["扌", "詹"], logic: "手肩承擔重荷。", story: "我們要一起分擔家裡的勞務。" },
    "扭": { grade: "2B", zhuyin: "ㄋㄧㄡˇ", comp: "hand", definition: "轉動。", phrases: ["扭轉"], sentence: "扭開水龍頭。", breakdown: ["扌", "丑"], logic: "用手轉動像打結。", story: "我不小心扭到了腳，現在要休息一下。" },
    "換": { grade: "2B", zhuyin: "ㄏㄨㄢˋ", comp: "hand", definition: "交換。", phrases: ["換衣服"], sentence: "我想要換一件衣服。", breakdown: ["扌", "奐"], logic: "手做變換動作。", story: "我和同學交換了漂亮的貼紙。" },
    "捧": { grade: "2B", zhuyin: "ㄆㄥˇ", comp: "hand", definition: "雙手托物。", phrases: ["捧著"], sentence: "他捧著果實。", breakdown: ["扌", "奉"], logic: "手恭敬托起。", story: "姐姐捧著一盆漂亮的花走進來。" },
    "掉": { grade: "2B", zhuyin: "ㄉㄧㄠˋ", comp: "hand", definition: "落下。", phrases: ["掉落"], sentence: "蘋果掉到地上。", breakdown: ["扌", "卓"], logic: "手拿不住落下了高處的物體。", story: "秋天到了，枯黃的樹葉從樹上掉下來。" },
    "抱": { grade: "2B", zhuyin: "ㄅㄠˋ", comp: "hand", definition: "用手臂圍著。", phrases: ["擁抱"], sentence: "媽媽抱著弟弟。", breakdown: ["扌", "包"], logic: "手臂像包袱一樣圍繞。", story: "見到好久不見的爺爺，我開心地給他一個大擁抱。" },
    "持": { grade: "2B", zhuyin: "ㄔˊ", comp: "hand", definition: "握住。", phrases: ["保持"], sentence: "請保持安靜。", breakdown: ["扌", "寺"], logic: "手守住目標。", story: "這項好習慣，我們要長久持下去。" },
    "操": { grade: "2B", zhuyin: "ㄘㄠ", comp: "hand", definition: "操作；練習。", phrases: ["操場"], sentence: "我們在操場玩。", breakdown: ["扌", "喿"], logic: "手拿著器材練習。", story: "體育課時，大家在操場上做體操。" },
    "搗": { grade: "2B", zhuyin: "ㄉㄠˇ", comp: "hand", definition: "打樁；弄亂。", phrases: ["搗亂"], sentence: "小猴子在搗蛋。", breakdown: ["扌", "島"], logic: "雙手像是在島嶼上不停敲擊。", story: "兔子在月亮上開心地搗著好吃的麻糬。" },

    // 3. 人部 (20 個)
    "你": { grade: "1A", zhuyin: "ㄋㄧˇ", comp: "person", definition: "第二人稱。", phrases: ["你好"], sentence: "認識你很高興。", breakdown: ["亻", "爾"], logic: "面前的一個人。", story: "我指著排在對面的人，就是『你』。" },
    "他": { grade: "1A", zhuyin: "ㄊㄚ", comp: "person", definition: "第三人稱。", phrases: ["他們"], sentence: "他在空地玩。", breakdown: ["亻", "也"], logic: "指別人。", story: "那邊那個正在踢球的小男生就是『他』。" },
    "們": { grade: "1A", zhuyin: "ㄇㄣ·", comp: "person", definition: "複數。", phrases: ["我們"], sentence: "我們是好朋友。", breakdown: ["亻", "門"], logic: "門口站了一群人。", story: "當很多人聚在一起時，我們用『們』。" },
    "人": { grade: "1A", zhuyin: "ㄖㄣˊ", comp: "person", definition: "人類。", phrases: ["大人"], sentence: "這邊有很多過路人。", breakdown: ["人"], logic: "象形字，人而立。", story: "世界上有很多種不同的人，大家要互相友愛。" },
    "像": { grade: "1B", zhuyin: "ㄒㄧㄤˋ", comp: "person", definition: "類似。", phrases: ["好像"], sentence: "他長得好像爸爸。", breakdown: ["亻", "象"], logic: "人看到的樣子。", story: "妹妹長得好像小天使一樣可愛。" },
    "什": { grade: "1B", zhuyin: "ㄕㄣˊ", comp: "person", definition: "疑問詞。", phrases: ["什麼"], sentence: "你在找什麼？", breakdown: ["亻", "十"], logic: "指很多的人事物。", story: "當我好奇發生了什麼事，我就會問個清楚。" },
    "但": { grade: "1B", zhuyin: "ㄉㄢˋ", comp: "person", definition: "不過。", phrases: ["但是"], sentence: "但願明天是晴天。", breakdown: ["亻", "旦"], logic: "太陽升起後人轉身。", story: "我本來想睡覺，但是好朋友來找我玩了。" },
    "借": { grade: "1B", zhuyin: "ㄐㄧㄝˋ", comp: "person", definition: "暫用他人財物。", phrases: ["借書"], sentence: "我向圖書館借了一本書。", breakdown: ["亻", "昔"], logic: "人與人之間過去的約定與物資流通。", story: "我的鉛筆斷了，同學好心借給我一枝。" },
    "住": { grade: "1B", zhuyin: "ㄓㄨˋ", comp: "person", definition: "居留。", phrases: ["居住"], sentence: "我就住在這裡。", breakdown: ["亻", "主"], logic: "人停留做主人。", story: "小鳥在樹上築了一個溫暖的巢住下來。" },
    "做": { grade: "1B", zhuyin: "ㄗㄨㄛˋ", comp: "person", definition: "工作；製造。", phrases: ["做事"], sentence: "我正在做功課。", breakdown: ["亻", "故"], logic: "人有目的地行動。", story: "放學後，我認真做今天的回家功課。" },
    "健": { grade: "1B", zhuyin: "ㄐㄧㄢˋ", comp: "person", definition: "強旺。", phrases: ["健康"], sentence: "多運動身體好。", breakdown: ["亻", "建"], logic: "建立強壯的身體。", story: "小馬每天跑步，身體長得很健壯。" },
    "候": { grade: "2A", zhuyin: "ㄏㄡˋ", comp: "person", definition: "時節；等待。", phrases: ["時候"], sentence: "什麼時候要出發？", breakdown: ["亻", "侯"], logic: "人拿箭射標靶。", story: "等候公車需要耐心，不要在路邊亂跑。" },
    "件": { grade: "2A", zhuyin: "ㄐㄧㄢˋ", comp: "person", definition: "量詞。", phrases: ["一件"], sentence: "這是一件好事。", breakdown: ["亻", "牛"], logic: "人分開牛來數數。", story: "我有三件漂亮的衣服，都是生日贈品。" },
    "伸": { grade: "2A", zhuyin: "ㄕㄣ", comp: "person", definition: "舒展。", phrases: ["伸手"], sentence: "伸出雙手拿球。", breakdown: ["亻", "申"], logic: "如閃電般伸直身。", story: "早晨起床後，伸個懶腰真舒服。" },
    "倒": { grade: "2A", zhuyin: "ㄉㄠˇ", comp: "person", definition: "傾跌。", phrases: ["跌倒"], sentence: "他不小心跌倒。", breakdown: ["亻", "到"], logic: "人身來到地面。", story: "水杯倒了，媽媽趕快拿抹布來擦。" },
    "介": { grade: "2A", zhuyin: "ㄐㄧㄝˋ", comp: "person", definition: "中間媒介。", phrases: ["介紹"], sentence: "老師介紹同學。", breakdown: ["人", "介"], logic: "人站在中間路口。", story: "透過老師的介紹，我認識了新夥伴。" },
    "保": { grade: "2A", zhuyin: "ㄅㄠˇ", comp: "person", definition: "守護。", phrases: ["保護"], sentence: "要保護大自然。", breakdown: ["亻", "呆"], logic: "人抱著小孩。", story: "這把傘能保護我不被大雨淋濕。" },
    "伴": { grade: "2B", zhuyin: "ㄅㄢˋ", comp: "person", definition: "夥同。", phrases: ["陪伴"], sentence: "謝謝你陪我玩。", breakdown: ["亻", "半"], logic: "人的一半，同伴。", story: "小狗是我最好的玩伴，我每天都帶牠去散步。" },
    "傳": { grade: "2B", zhuyin: "ㄔㄨㄢˊ", comp: "person", definition: "遞送。", phrases: ["傳球"], sentence: "把球傳給我。", breakdown: ["亻", "專"], logic: "專心將事物由這人交給那人。", story: "大隊接力時，我們要穩穩地把接力棒傳給下一位。" },
    "信": { grade: "2B", zhuyin: "ㄒㄧㄣˋ", comp: "person", definition: "誠實；信件。", phrases: ["相信"], sentence: "這是一封信。", breakdown: ["亻", "言"], logic: "人說出的話有信用。", story: "我寫了一張信紙，寄給遠方的爺爺。" },

    // 4. 口部 (33 個)
    "吹": { grade: "1A", zhuyin: "ㄔㄨㄟ", comp: "mouth", definition: "呼氣。", phrases: ["吹氣"], sentence: "涼風吹過來。", breakdown: ["口", "欠"], logic: "合口呵氣。", story: "吹生日蠟燭前，我會先許一個願。" },
    "問": { grade: "1A", zhuyin: "ㄨㄣˋ", comp: "mouth", definition: "請教。", phrases: ["問題"], sentence: "問問題不要害羞。", breakdown: ["門", "口"], logic: "在門邊張口打聽。", story: "不懂的事情開口問一問，煩惱就消了。" },
    "叫": { grade: "1A", zhuyin: "ㄐㄧㄠˋ", comp: "mouth", definition: "呼喊。", phrases: ["大叫"], sentence: "不要在醫院叫喊。", breakdown: ["口", "丩"], logic: "嘴巴發出長聲。", story: "小黑狗看見壞人就會汪汪大叫。" },
    "嗎": { grade: "1A", zhuyin: "ㄇㄚ·", comp: "mouth", definition: "疑問詞。", phrases: ["好嗎"], sentence: "媽媽在家嗎？", breakdown: ["口", "馬"], logic: "張口詢問之音。", story: "這件事我做得好嗎？請大家告訴我。" },
    "哈": { grade: "1A", zhuyin: "ㄏㄚ", comp: "mouth", definition: "笑聲。", phrases: ["哈哈"], sentence: "大家笑得哈哈叫。", breakdown: ["口", "合"], logic: "笑得合不攏嘴。", story: "笑聲哈哈笑個不停，全家都很開心。" },
    "右": { grade: "1A", zhuyin: "ㄧㄡˋ", comp: "mouth", definition: "方位。", phrases: ["右手"], sentence: "請靠右邊坐。", breakdown: ["𠂇", "口"], logic: "手送食物入口。", story: "我用右手拿筷子吃飯。" },
    "和": { grade: "1A", zhuyin: "ㄏㄜˊ", comp: "mouth", definition: "平順；共同。", phrases: ["平和"], sentence: "我和你去公園。", breakdown: ["禾", "口"], logic: "口吃禾穀而安。", story: "我和妹妹一起分享甜甜的糖果。" },
    "呀": { grade: "1B", zhuyin: "ㄧㄚ·", comp: "mouth", definition: "助詞。", phrases: ["哎呀"], sentence: "這花真漂亮呀！", breakdown: ["口", "牙"], logic: "牙口發出讚嘆。", story: "哎呀！我不小心把墨水翻倒了。" },
    "唱": { grade: "1B", zhuyin: "ㄔㄤˋ", comp: "mouth", definition: "發聲歌詠。", phrases: ["唱歌"], sentence: "小鳥在唱歌。", breakdown: ["口", "昌"], logic: "口發昌盛美音。", story: "姊姊最喜歡一邊跳舞一邊唱著好聽的歌。" },
    "呢": { grade: "1B", zhuyin: "ㄋㄜ·", comp: "mouth", definition: "助詞。", phrases: ["你在哪呢"], sentence: "他在做什麼呢？", breakdown: ["口", "尼"], logic: "口部發音語氣。", story: "太陽公公在哪裡呢？他被雲遮住了。" },
    "吧": { grade: "1B", zhuyin: "ㄅㄚ·", comp: "mouth", definition: "商量助詞。", phrases: ["走吧"], sentence: "一塊去玩吧。", breakdown: ["口", "巴"], logic: "徵詢語氣之音。", story: "天色不早了，我們趕快回家吃飯吧。" },
    "啊": { grade: "1B", zhuyin: "ㄚ·", comp: "mouth", definition: "嘆詞。", phrases: ["啊對了"], sentence: "啊！這張畫真好。", breakdown: ["口", "阿"], logic: "張大嘴嘆氣。", story: "啊！一轉眼，小樹苗就長高了。" },
    "咬": { grade: "1B", zhuyin: "ㄧㄠˇ", comp: "mouth", definition: "嚼斷。", phrases: ["咬斷"], sentence: "小狗咬住骨頭。", breakdown: ["口", "交"], logic: "牙齒上下交錯。", story: "大口咬下脆脆的蘋果，真好玩。" },
    "吃": { grade: "1B", zhuyin: "ㄔ", comp: "mouth", definition: "進食。", phrases: ["吃飯"], sentence: "我喜歡吃西瓜。", breakdown: ["口", "乞"], logic: "口求食物。", story: "小雞在地上找毛毛蟲吃。" },
    "哭": { grade: "1B", zhuyin: "ㄎㄨ", comp: "mouth", definition: "悲泣。", phrases: ["哭聲"], sentence: "妹妹跌倒哭聲。", breakdown: ["口", "口", "犬"], logic: "像狗叫樣流淚。", story: "好朋友要轉學了，我心裡很難過想哭。" },
    "呱": { grade: "2A", zhuyin: "ㄍㄨㄚ", comp: "mouth", definition: "擬聲詞。", phrases: ["呱呱叫"], sentence: "青蛙在唱歌。", breakdown: ["口", "瓜"], logic: "口發刮聲。", story: "呱呱呱，池塘裡的鴨子在找玩伴。" },
    "聞": { grade: "2A", zhuyin: "ㄨㄣˊ", comp: "mouth", definition: "鼻嗅；聽見。", phrases: ["新聞"], sentence: "我聞到花香。", breakdown: ["門", "耳"], logic: "在門邊耳聽。", story: "遠處傳來了好聽的音樂，我仔細聽聞。" },
    "嘴": { grade: "2A", zhuyin: "ㄗㄨㄟˇ", comp: "mouth", definition: "口部。", phrases: ["嘴巴"], sentence: "說話要閉嘴。", breakdown: ["口", "觜"], logic: "發聲的部位。", story: "說話時，最重要的是這張能說好話的嘴。" },
    "名": { grade: "2A", zhuyin: "ㄇㄧㄥˊ", comp: "mouth", definition: "名稱。", phrases: ["名字"], sentence: "考卷寫上名字。", breakdown: ["夕", "口"], logic: "傍晚喊名。", story: "請大聲報出你的名字，讓大家認識你。" },
    "哪": { grade: "2A", zhuyin: "ㄋㄚˇ", comp: "mouth", definition: "詢問。", phrases: ["哪裡"], sentence: "你去過哪裡？", breakdown: ["口", "那"], logic: "問在那邊的事。", story: "哪種顏色的彩虹最漂亮？大家都想知道。" },
    "盒": { grade: "2A", zhuyin: "ㄏㄜˊ", comp: "mouth", definition: "小型盛物器。", phrases: ["盒子"], sentence: "糖果在盒子裡。", breakdown: ["合", "皿"], logic: "器皿蓋合。", story: "這是我珍藏貼紙的小盒子。" },
    "口": { grade: "2A", zhuyin: "ㄎㄡˇ", comp: "mouth", definition: "嘴；門。", phrases: ["口罩"], sentence: "戴好口罩。", breakdown: ["口"], logic: "象形，張開的嘴。", story: "口裡說出的話要甜甜的，大家才會喜歡你。" },
    "對": { grade: "2A", zhuyin: "ㄉㄨㄟˋ", comp: "mouth", definition: "正確的；面向。", phrases: ["答對"], sentence: "你這題答對了。", breakdown: ["業", "寸"], logic: "對準目標答理。", story: "兩隻小鳥面對面唱著好聽的歌。" },
    "念": { grade: "2A", zhuyin: "ㄋㄧㄢˋ", comp: "mouth", definition: "思慮；朗讀。", phrases: ["念書"], sentence: "大聲念課文。", breakdown: ["今", "心"], logic: "心中時刻記掛的。", story: "把生字大聲地念出來，就能永遠記在心裡。" },
    "巴": { grade: "2A", zhuyin: "ㄅㄚ", comp: "mouth", definition: "黏附；期盼。", phrases: ["尾巴"], sentence: "狗搖尾巴。", breakdown: ["巴"], logic: "像蛇捲曲附著。", story: "小貓咪的尾巴毛茸茸的，一直搖來搖去。" },
    "哇": { grade: "2B", zhuyin: "ㄨㄚ", comp: "mouth", definition: "嘆詞。", phrases: ["哇！"], sentence: "哇！這畫得真美。", breakdown: ["口", "圭"], logic: "開口驚嘆。", story: "看到大象表演，小朋友們都驚呼：哇！" },
    "喝": { grade: "2B", zhuyin: "ㄏㄜ", comp: "mouth", definition: "飲；喊。", phrases: ["喝水"], sentence: "多喝白開水。", breakdown: ["口", "曷"], logic: "口渴而飲。", story: "口渴時喝一杯果汁，感覺真清爽。" },
    "呵": { grade: "2B", zhuyin: "ㄏㄜ", comp: "mouth", definition: "笑；罵。", phrases: ["呵呵"], sentence: "他大笑呵呵。", breakdown: ["口", "可"], logic: "呼氣之聲。", story: "看到小動物逗趣的模樣，我忍不住呵呵笑。" },
    "呼": { grade: "2B", zhuyin: "ㄏㄨ", comp: "mouth", definition: "吐氣。", phrases: ["呼吸"], sentence: "深呼吸一口氣。", breakdown: ["口", "乎"], logic: "發聲呼呼氣。", story: "森林裡的風呼呼地吹著，像在跟我們說話。" },
    "吵": { grade: "2B", zhuyin: "ㄔㄠˇ", comp: "mouth", definition: "爭鬥；亂聲。", phrases: ["吵鬧"], sentence: "不要吵鄰居。", breakdown: ["口", "少"], logic: "少數人在爭執。", story: "鄰居家養的小鳥一直吵個不停。" },
    "吐": { grade: "2B", zhuyin: "ㄊㄨˇ", comp: "mouth", definition: "由口排出。", phrases: ["吐出"], sentence: "把籽吐掉。", breakdown: ["口", "土"], logic: "口中排出物。", story: "蠶寶寶吐出了細細的絲，蓋了一個溫暖的家。" },
    "嚇": { grade: "2B", zhuyin: "ㄒㄧㄚ", comp: "mouth", definition: "驚恐。", phrases: ["嚇人"], sentence: "雷聲嚇了一跳。", breakdown: ["口", "赫"], logic: "發出赫赫吼聲。", story: "那個大影子突然閃過，嚇得我趕快跑。" },
    "告": { grade: "2B", zhuyin: "ㄍㄠˋ", comp: "mouth", definition: "告知。", phrases: ["告訴"], sentence: "請告訴我秘密。", breakdown: ["牛", "口"], logic: "牛觸角口述。", story: "我要把這個好消息大聲告訴所有人。" },

    // 5. 水部 (30 個)
    "水": { grade: "1A", zhuyin: "ㄕㄨㄟˇ", comp: "water", definition: "透明液體。", phrases: ["喝水"], sentence: "多喝水才健康。", breakdown: ["水"], logic: "象形流動。", story: "高山流下的泉水，變成了壯闊的大海。" },
    "沒": { grade: "1A", zhuyin: "ㄇㄟˊ", comp: "water", definition: "無；沉沒。", phrases: ["沒有"], sentence: "我沒有帶錢。", breakdown: ["氵", "殳"], logic: "沉入水中。", story: "小石子噗通一聲沒入水中，不見蹤影了。" },
    "泡": { grade: "1A", zhuyin: "ㄆㄠˋ", comp: "water", definition: "氣泡。", phrases: ["泡泡"], sentence: "我愛吹泡泡。", breakdown: ["氵", "包"], logic: "水邊冒出包囊。", story: "浴盆裡的小船載著無數個白白的小泡泡。" },
    "池": { grade: "1A", zhuyin: "ㄔˊ", comp: "water", definition: "蓄水池。", phrases: ["池塘"], sentence: "池子有大魚。", breakdown: ["氵", "也"], logic: "水聚在一起。", story: "我們去公園的池塘看小鴨子游泳。" },
    "涼": { grade: "1B", zhuyin: "ㄌㄧㄤˊ", comp: "water", definition: "稍冷。", phrases: ["涼快"], sentence: "風很涼快。", breakdown: ["氵", "京"], logic: "水在陰涼處。", story: "一走進陰涼的樹林，感覺非常涼爽。" },
    "河": { grade: "1B", zhuyin: "ㄏㄜˊ", comp: "water", definition: "渠道。", phrases: ["河流"], sentence: "大河好長。", breakdown: ["氵", "可"], logic: "通航的水道。", story: "一條細長的小河，靜靜流過村莊門口。" },
    "游": { grade: "1B", zhuyin: "ㄧㄡˊ", comp: "water", definition: "水中行進。", phrases: ["游泳"], sentence: "海裡有人在游。", breakdown: ["氵", "斿"], logic: "隨波漂流。", story: "彩色的小魚在珊瑚礁間游來游去。" },
    "溫": { grade: "1B", zhuyin: "ㄨㄣ", comp: "water", definition: "微熱。", phrases: ["溫暖"], sentence: "洗熱水澡。", breakdown: ["氵", "昷"], logic: "適度的熱水。", story: "冬天泡溫泉是世界上最舒服的事情。" },
    "漂": { grade: "1B", zhuyin: "ㄆㄧㄠ", comp: "water", definition: "浮在水面；美。", phrases: ["漂亮"], sentence: "花朵真美。", breakdown: ["氵", "票"], logic: "浮而不沉。", story: "湖面上漂著一隻白色的小木船。" },
    "滿": { grade: "2A", zhuyin: "ㄇㄢˇ", comp: "water", definition: "充足。", phrases: ["充滿"], sentence: "水杯滿了。", breakdown: ["氵", "𦐇"], logic: "溢出的水量。", story: "全班同學都滿意這份豐盛的點心。" },
    "消": { grade: "2A", zhuyin: "ㄒㄧㄠ", comp: "water", definition: "散退。", phrases: ["消失"], sentence: "幻覺消了。", breakdown: ["氵", "肖"], logic: "水使焦灼散去。", story: "這個夏天的熱氣，隨著一陣大雨消退了。" },
    "法": { grade: "2A", zhuyin: "ㄈㄚˇ", comp: "water", definition: "規則。", phrases: ["方法"], sentence: "法網難逃。", breakdown: ["氵", "去"], logic: "流水必經之路。", story: "我們要遵守學校的法規，當個好學生。" },
    "灘": { grade: "2A", zhuyin: "ㄊㄢ", comp: "water", definition: "水邊的沙地。", phrases: ["沙灘"], sentence: "我們在沙灘玩。", breakdown: ["氵", "難"], logic: "水流遇到阻礙形成的淺地。", story: "週末時，爸爸帶我們去沙灘上蓋了漂亮的沙堡。" },
    "海": { grade: "2A", zhuyin: "ㄏㄞˇ", comp: "water", definition: "各大洋。", phrases: ["大海"], sentence: "看看大海。", breakdown: ["氵", "每"], logic: "百川之母。", story: "爸爸帶我去海邊，我撿了很多漂亮的石頭。" },
    "溪": { grade: "2A", zhuyin: "ㄒㄧ", comp: "water", definition: "小水道。", phrases: ["小溪"], sentence: "溪水在流。", breakdown: ["氵", "奚"], logic: "山谷細流。", story: "小溪裡住著許多螃蟹和小魚。" },
    "活": { grade: "2A", zhuyin: "ㄏㄨㄛˊ", comp: "water", definition: "生動。", phrases: ["活動"], sentence: "生活精彩。", breakdown: ["氵", "舌"], logic: "舌口分泌液水。", story: "大自然中處處可見活潑飛舞的蝴蝶。" },
    "清": { grade: "2A", zhuyin: "ㄑㄧㄥ", comp: "water", definition: "淨。", phrases: ["清澈"], sentence: "河水清淨。", breakdown: ["氵", "青"], logic: "水色如青天。", story: "早晨把家門前打掃清爽，心情真好。" },
    "沖": { grade: "2A", zhuyin: "ㄔㄨㄥ", comp: "water", definition: "猛灌。", phrases: ["沖洗"], sentence: "沖走汙泥。", breakdown: ["氵", "中"], logic: "水注入中心。", story: "大浪沖刷著岸邊的礁石，非常壯觀。" },
    "澡": { grade: "2A", zhuyin: "ㄗㄠˇ", comp: "water", definition: "洗滌。", phrases: ["洗澡"], sentence: "愛洗澡。", breakdown: ["氵", "喿"], logic: "在喧嘩中洗浴。", story: "晚上回家的第一件事就是洗澡，乾淨又衛生。" },
    "浴": { grade: "2A", zhuyin: "ㄩˋ", comp: "water", definition: "浸。", phrases: ["浴室"], sentence: "入浴洗澡。", breakdown: ["氵", "谷"], logic: "在山谷中集水。", story: "小鴨子在池子裡沐浴，快樂地點點頭。" },
    "減": { grade: "2A", zhuyin: "ㄐㄧㄢˇ", comp: "water", definition: "少去。", phrases: ["減少"], sentence: "減肥。", breakdown: ["氵", "咸"], logic: "水被蒸曬而減。", story: "把不需要的東西減去，生活會變得更清爽。" },
    "浮": { grade: "2A", zhuyin: "ㄈㄨˊ", comp: "water", definition: "漂立。", phrases: ["浮力"], sentence: "漂浮。", breakdown: ["氵", "孚"], logic: "手抱蛋浮著。", story: "黃色小鴨浮在泳池中，小朋友都想抓牠。" },
    "波": { grade: "2A", zhuyin: "ㄅㄛ", comp: "water", definition: "起伏。", phrases: ["波浪"], sentence: "湖面起波波。", breakdown: ["氵", "皮"], logic: "如皺紋（皮）的水面。", story: "微風吹過湖面，泛起一圈圈漂亮的波紋。" },
    "滴": { grade: "2B", zhuyin: "ㄉㄧ", comp: "water", definition: "水珠。", phrases: ["滴答"], sentence: "水在一滴滴落。", breakdown: ["氵", "帝"], logic: "如雨之主。", story: "我在荷葉上看到幾滴亮晶晶的小露水。" },
    "浪": { grade: "2B", zhuyin: "ㄌㄤˋ", comp: "water", definition: "大波濤。", phrases: ["浪花"], sentence: "浪大。", breakdown: ["氵", "良"], logic: "奔流的水量。", story: "一陣大浪捲起了白亮亮的浪花。" },
    "渴": { grade: "2B", zhuyin: "ㄎㄜˇ", comp: "water", definition: "口乾。", phrases: ["口渴"], sentence: "喝水止渴。", breakdown: ["氵", "曷"], logic: "水分告竭。", story: "我現在非常渴，想喝一杯冰涼的水。" },
    "洗": { grade: "2B", zhuyin: "ㄒㄧˇ", comp: "water", definition: "除汙。", phrases: ["洗手"], sentence: "衣服洗好了。", breakdown: ["氵", "先"], logic: "優先除垢。", story: "小狗狗在草地上玩髒了，我要幫牠洗個澡。" },
    "泥": { grade: "2B", zhuyin: "ㄋㄧˊ", comp: "water", definition: "軟土。", phrases: ["泥巴"], sentence: "泥土。", breakdown: ["氵", "尼"], logic: "水土凝結。", story: "下大雨的時候，山路變成了滑滑的爛泥。" },
    "漸": { grade: "2B", zhuyin: "ㄐㄧㄢˋ", comp: "water", definition: "慢進。", phrases: ["漸漸"], sentence: "天黑了。", breakdown: ["氵", "斬"], logic: "如斬斷般進入。", story: "隨著春天來到，樹葉漸漸變綠了。" },
    "淚": { grade: "2B", zhuyin: "ㄌㄟˋ", comp: "water", definition: "眼水。", phrases: ["眼淚"], sentence: "不要流淚。", breakdown: ["氵", "戾"], logic: "眼冒出的水。", story: "看完感人的故事袋電影後，大家都流下了眼淚。" },

    // 6. 木部 (11 個)
    "棵": { grade: "1B", zhuyin: "ㄎㄜ", comp: "wood", definition: "量詞。", phrases: ["一棵樹"], sentence: "這是一棵大樹。", breakdown: ["木", "果"], logic: "按木果實計數。", story: "爺爺在後院種了一棵紅紅的小蘋果樹。" },
    "樹": { grade: "1B", zhuyin: "ㄕㄨˋ", comp: "wood", definition: "木本植物。", phrases: ["樹葉"], sentence: "大樹好高。", breakdown: ["木", "尌"], logic: "鼓舞向上的木。", story: "小松鼠在高的樹枝上跑來跑去。" },
    "桌": { grade: "1B", zhuyin: "ㄓㄨㄛ", comp: "wood", definition: "桌子。", phrases: ["書桌"], sentence: "桌子很大。", breakdown: ["木", "𠔁"], logic: "太陽下木台。", story: "這張圓圓的小桌子，是我們全家聚會的地方。" },
    "樣": { grade: "2A", zhuyin: "ㄧㄤˋ", comp: "wood", definition: "標準。", phrases: ["樣子"], sentence: "一樣的書。", breakdown: ["木", "羕"], logic: "木頭的紋理。", story: "我要朝著好榜樣努力進步。" },
    "材": { grade: "2A", zhuyin: "ㄘㄞˊ", comp: "wood", definition: "原料。", phrases: ["材料"], sentence: "做家事的材料。", breakdown: ["木", "才"], logic: "木裁切可用。", story: "這塊木材很厚實，可以用來做一張大桌子。" },
    "桶": { grade: "2A", zhuyin: "ㄊㄨㄥˇ", comp: "wood", definition: "圓形容器。", phrases: ["水桶"], sentence: "提著水桶。", breakdown: ["木", "甬"], logic: "木工用具。", story: "我們提著紅色的小水桶，去海邊裝沙子玩。" },
    "木": { grade: "2B", zhuyin: "ㄇㄨˋ", comp: "wood", definition: "樹木。", phrases: ["木頭"], sentence: "木柴。", breakdown: ["木"], logic: "象形，根葉齊。", story: "爺爺在山上砍了一些木柴來生火。" },
    "植": { grade: "2B", zhuyin: "ㄓˊ", comp: "wood", definition: "種。", phrases: ["植物"], sentence: "澆水。", breakdown: ["木", "直"], logic: "直立的木。", story: "春天的校園裡，老師帶著大家一起植樹。" },
    "根": { grade: "2B", zhuyin: "ㄍㄣ", comp: "wood", definition: "基礎。", phrases: ["樹根"], sentence: "樹牢靠。", breakdown: ["木", "艮"], logic: "難動的底部。", story: "這棵老松樹有著像龍鬚一樣的長根。" },
    "棍": { grade: "2B", zhuyin: "ㄍㄨㄣˋ", comp: "wood", definition: "條狀。", phrases: ["棒子"], sentence: "防身。", breakdown: ["木", "昆"], logic: "長長的木。", story: "小羊在草地上，主人拿著細木棍在指路。" },
    "棒": { grade: "2B", zhuyin: "ㄅㄤˋ", comp: "wood", definition: "優；棍。", phrases: ["好棒"], sentence: "你真棒。", breakdown: ["木", "奉"], logic: "雙手奉上的美木。", story: "你的體操動作做得非常標準，真的太棒了！" },

    // 7. 足部 (10 個)
    "走": { grade: "1A", zhuyin: "ㄗㄡˇ", comp: "foot", definition: "行。", phrases: ["走路"], sentence: "路要慢慢走。", breakdown: ["土", "足"], logic: "腳在地上行。", story: "每天吃完飯，全家人都去公園散步走走。" },
    "跑": { grade: "1A", zhuyin: "ㄆㄠˇ", comp: "foot", definition: "急行。", phrases: ["跑步"], sentence: "在操場跑。", breakdown: ["足", "包"], logic: "腳步飛快像包裹一樣捲起。", story: "大隊接力時，我們盡全力在跑道上飛奔。" },
    "路": { grade: "1B", zhuyin: "ㄌㄨˋ", comp: "foot", definition: "道。", phrases: ["馬路"], sentence: "大路廣闊。", breakdown: ["足", "各"], logic: "每個人都走的地方。", story: "回家的路有很多條，但我最喜歡這條有小花的。" },
    "跳": { grade: "1B", zhuyin: "ㄊㄧㄠˋ", comp: "foot", definition: "蹦。", phrases: ["跳舞"], sentence: "跳繩子。", breakdown: ["足", "兆"], logic: "腳快速躍動。", story: "老師教我們學習跳繩的技巧。" },
    "步": { grade: "1B", zhuyin: "ㄅㄨˋ", comp: "foot", definition: "距。", phrases: ["腳步"], sentence: "走一步。", breakdown: ["止", "少"], logic: "左右分跨腳。", story: "讓我們配合著音樂，一步一步地跳舞吧。" },
    "越": { grade: "2A", zhuyin: "ㄩㄝˋ", comp: "foot", definition: "過。", phrases: ["越過"], sentence: "穿過圍牆。", breakdown: ["走", "戉"], logic: "腳跨過斧頭界點。", story: "月亮越升越高，像大大的白玉盤。" },
    "腳": { grade: "2A", zhuyin: "ㄐㄧㄠˇ", comp: "foot", definition: "下肢。", phrases: ["腳底"], sentence: "腳很大。", breakdown: ["月", "腳"], logic: "足部肉骨。", story: "不小心我的腳踢到了一顆小石子。" },
    "跡": { grade: "2A", zhuyin: "ㄐㄧ", comp: "foot", definition: "痕。", phrases: ["遺留"], sentence: "有印記。", breakdown: ["足", "亦"], logic: "在那留下的腳印。", story: "大雨過後，泥土上會發現小貓的腳印跡。" },
    "踢": { grade: "2B", zhuyin: "ㄊㄧ", comp: "foot", definition: "擊。", phrases: ["踢球"], sentence: "去操場踢球。", breakdown: ["足", "易"], logic: "腳隨心意擊發。", story: "哥哥最喜歡在陽光下跟好朋友踢足球。" },
    "足": { grade: "2B", zhuyin: "ㄗㄨˊ", comp: "foot", definition: "腳；飽。", phrases: ["足球"], sentence: "份量足。", breakdown: ["足"], logic: "象形，膝下部。", story: "運動要適量，充足的睡眠也很重要。" },

    // 8. 心部 (15 個)
    "心": { grade: "1A", zhuyin: "ㄒㄧㄣ", comp: "heart", definition: "器官；中。", phrases: ["開心"], sentence: "今天真高興。", breakdown: ["心"], logic: "象形臟器。", story: "我們的心要像一盞燈，照亮自己也幫助別人。" },
    "想": { grade: "1A", zhuyin: "ㄒㄧㄤˇ", comp: "heart", definition: "思慮。", phrases: ["想法"], sentence: "我想出去玩。", breakdown: ["相", "心"], logic: "在心裡看眾相。", story: "天色不早了，我正在想明天要穿哪件衣服。" },
    "快": { grade: "1B", zhuyin: "ㄎㄨㄞˋ", comp: "heart", definition: "捷；樂。", phrases: ["快步"], sentence: "火車快跑。", breakdown: ["忄", "夬"], logic: "心跳劇烈。", story: "小烏龜爬得慢，但心裡很快樂。" },
    "急": { grade: "1B", zhuyin: "ㄐㄧˊ", comp: "heart", definition: "焦。", phrases: ["焦急"], sentence: "別著急。", breakdown: ["⺈", "心"], logic: "被事情抓緊了。", story: "不要心急，我們慢慢來一定做得好。" },
    "情": { grade: "1B", zhuyin: "ㄑㄧㄥˊ", comp: "heart", definition: "緒。", phrases: ["心情"], sentence: "他很高興。", breakdown: ["忄", "青"], logic: "心如春草青嫩。", story: "謝謝你這段時間的照顧與深情厚誼。" },
    "忍": { grade: "1B", zhuyin: "ㄖㄣˇ", comp: "heart", definition: "耐。", phrases: ["忍耐"], sentence: "學著忍讓。", breakdown: ["刃", "心"], logic: "心上有刀刃。", story: "這盤苦瓜雖然苦，我要忍著吃掉它。" },
    "忘": { grade: "1B", zhuyin: "ㄨㄤˋ", comp: "heart", definition: "失憶。", phrases: ["忘記"], sentence: "我忘了帶書。", breakdown: ["亡", "心"], logic: "心死記不住。", story: "不要讓美好的回憶都被遺忘了。" },
    "怎": { grade: "2A", zhuyin: "ㄗㄣˇ", comp: "heart", definition: "何。", phrases: ["怎麼"], sentence: "怎麼辦？", breakdown: ["乍", "心"], logic: "心感突然遲疑。", story: "你是在怎麼知道這個神奇秘密的？" },
    "意": { grade: "2A", zhuyin: "ㄧˋ", comp: "heart", definition: "願。", phrases: ["注意"], sentence: "請注意看路。", breakdown: ["音", "心"], logic: "心底發出聲。", story: "請大聲說出你這次參賽的真誠意願。" },
    "思": { grade: "2A", zhuyin: "ㄙ", comp: "heart", definition: "掛念。", phrases: ["思念"], sentence: "我想外公。", breakdown: ["田", "心"], logic: "心在田中思維。", story: "我的心思全在暑假要出國玩的那趟旅行。" },
    "怪": { grade: "2A", zhuyin: "ㄍㄨㄞˋ", comp: "heart", definition: "異；怨。", phrases: ["奇怪"], sentence: "沒見過這種馬。", breakdown: ["忄", "圣"], logic: "心感聖異跡。", story: "這道味道聞起來怪怪的，可能壞掉了。" },
    "總": { grade: "2B", zhuyin: "ㄗㄨㄥˇ", comp: "heart", definition: "聚合；老。", phrases: ["總是"], sentence: "他總是樂於助人。", breakdown: ["忄", "忩"], logic: "心隨萬物凝聚。", story: "他總是樂於幫助班上遇到困難的同學。" },
    "慢": { grade: "2B", zhuyin: "ㄇㄢˋ", comp: "heart", definition: "遲；傲。", phrases: ["慢點"], sentence: "火車開得慢。", breakdown: ["忄", "曼"], logic: "心情悠長緩慢。", story: "蝸牛雖然爬得慢，但他卻看遍了風景。" },
    "煩": { grade: "2B", zhuyin: "ㄈㄢˊ", comp: "heart", definition: "亂。", phrases: ["煩惱"], sentence: "別擔心了。", breakdown: ["火", "頁"], logic: "頭部（頁）發熱（火）。", story: "這次的功課題目真多，看到就覺得心煩。" },
    "怕": { grade: "2B", zhuyin: "ㄆㄚˋ", comp: "heart", definition: "懼。", phrases: ["害怕"], sentence: "別怕天黑。", breakdown: ["忄", "白"], logic: "心裡一片空（白）。", story: "不要害怕失敗，勇於嘗試才是好漢子。" },

    // 9. 言部 (17 個)
    "請": { grade: "1A", zhuyin: "ㄑㄧㄥˇ", comp: "speech", definition: "邀。", phrases: ["請坐"], sentence: "請多多指教。", breakdown: ["言", "青"], logic: "言如春意清客。", story: "當你要找人幫忙時，先說一聲：拜託請幫忙。" },
    "說": { grade: "1A", zhuyin: "ㄕㄨㄛ", comp: "speech", definition: "講。", phrases: ["說話"], sentence: "講好話。", breakdown: ["言", "兌"], logic: "出口心意。", story: "他說故事的能力強得驚人，大家聽得入迷。" },
    "誰": { grade: "1A", zhuyin: "ㄕㄨㄟˊ", comp: "speech", definition: "何人。", phrases: ["是誰"], sentence: "有人敲門。", breakdown: ["言", "隹"], logic: "言詢如鳥瞬逝之人。", story: "誰在門口敲門敲得叮叮咚咚響？" },
    "寫": { grade: "1B", zhuyin: "ㄒㄧㄝˇ", comp: "speech", definition: "紀錄。", phrases: ["寫字"], sentence: "練字。", breakdown: ["宀", "舄"], logic: "在室內紀錄。", story: "他正在大聲讀著昨晚寫下的那封情書。" },
    "話": { grade: "1B", zhuyin: "ㄏㄨㄚˋ", comp: "speech", definition: "談。", phrases: ["電話"], sentence: "講公道話。", breakdown: ["言", "舌"], logic: "言在舌出。", story: "聽我說完一句真心話，你再決定。" },
    "課": { grade: "1B", zhuyin: "ㄎㄜˋ", comp: "speech", definition: "學業。", phrases: ["上課"], sentence: "認真聽講。", breakdown: ["言", "果"], logic: "言語之實。", story: "老師教我們學習這一課最深入的單字。" },
    "記": { grade: "1B", zhuyin: "ㄐㄧˋ", comp: "speech", definition: "錄。", phrases: ["記得"], sentence: "記住好事。", breakdown: ["言", "己"], logic: "留於自己。", story: "這是一件非常難忘的事情，我會銘記在心。" },
    "試": { grade: "1B", zhuyin: "ㄕˋ", comp: "speech", definition: "驗。", phrases: ["嘗試"], sentence: "考試要細心。", breakdown: ["言", "式"], logic: "言如儀式檢核。", story: "大家都摩拳擦掌，想去試試看自己的身手。" },
    "習": { grade: "2A", zhuyin: "ㄒㄧˊ", comp: "speech", definition: "學習。", phrases: ["習慣"], sentence: "學好習慣。", breakdown: ["羽", "白"], logic: "鳥在白日練飛。", story: "溫故而知新，每晚都要好好複習功課。" },
    "證": { grade: "2A", zhuyin: "ㄓㄥˋ", comp: "speech", definition: "據。", phrases: ["證明"], sentence: "證據不足。", breakdown: ["言", "登"], logic: "言記錄上冊（登）。", story: "學生證是我們進入校門的安全證明文件。" },
    "認": { grade: "2A", zhuyin: "ㄖㄣˋ", comp: "speech", definition: "辨。", phrases: ["認真"], sentence: "我不認識他。", breakdown: ["言", "忍"], logic: "言領會於心。", story: "他對這位認真的老師非常有禮貌。" },
    "識": { grade: "2A", zhuyin: "ㄕˋ", comp: "speech", definition: "曉。", phrases: ["知識"], sentence: "學知識。", breakdown: ["言", "戠"], logic: "言語之誌。", story: "我們都要學習識字，才能讀懂好文獻。" },
    "讀": { grade: "2A", zhuyin: "ㄉㄨˊ", comp: "speech", definition: "誦。", phrases: ["讀書"], sentence: "愛讀好書。", breakdown: ["言", "賣"], logic: "言交流傳（賣）。", story: "他正大聲讀出課本裡動人的故事情節。" },
    "謎": { grade: "2A", zhuyin: "ㄇㄧˊ", comp: "speech", definition: "玩隱題。", phrases: ["謎底"], sentence: "猜個謎。", breakdown: ["言", "迷"], logic: "令人著迷之言。", story: "猜謎是我們最喜歡玩的家庭小聚會活動。" },
    "答": { grade: "2A", zhuyin: "ㄉㄚˊ", comp: "speech", definition: "響應。", phrases: ["回答"], sentence: "答應他。", breakdown: ["竹", "合"], logic: "合契而對。", story: "這份答卷寫得非常完美，請大家掌聲鼓勵。" },
    "訴": { grade: "2B", zhuyin: "ㄙㄨˋ", comp: "speech", definition: "告知。", phrases: ["告訴"], sentence: "你要訴說什麼？", breakdown: ["言", "斥"], logic: "當眾口訴（斥）。", story: "請把你的滿腹委屈都向媽媽訴說吧。" },
    "託": { grade: "2B", zhuyin: "ㄊㄨㄛ", comp: "speech", definition: "代理。", phrases: ["拜託"], sentence: "委託他辦事。", breakdown: ["言", "乇"], logic: "言之寄託（乇）。", story: "這是一份重大的委託，我們一定要達成使命。" },

    // 10. 艸部 (8 個)
    "草": { grade: "1A", zhuyin: "ㄘㄠˇ", comp: "grass", definition: "植物。", phrases: ["綠草"], sentence: "地上長草。", breakdown: ["艸", "早"], logic: "早起之鮮綠。", story: "小兔最喜歡在綠油油的草坪玩耍。" },
    "花": { grade: "1A", zhuyin: "ㄏㄨㄚ", comp: "grass", definition: "花蕾。", phrases: ["花朵"], sentence: "花開得美。", breakdown: ["艸", "化"], logic: "草木之變遷。", story: "春天到了，萬物都綻放出漂亮花朵。" },
    "葉": { grade: "1B", zhuyin: "ㄧㄝˋ", comp: "grass", definition: "葉片。", phrases: ["樹葉"], sentence: "掃落葉。", breakdown: ["艸", "世", "木"], logic: "木之千秋繁延波。", story: "秋天到了，金黃色的枯葉鋪滿小徑。" },
    "菜": { grade: "2A", zhuyin: "ㄘㄞˋ", comp: "grass", definition: "食用草木。", phrases: ["蔬菜"], sentence: "多吃菜好。", breakdown: ["艸", "采"], logic: "摘收草本。", story: "這是一盤媽媽親手炒的新鮮小白菜。" },
    "苔": { grade: "2A", zhuyin: "ㄊㄞˊ", comp: "grass", definition: "青苔。", phrases: ["苔蘚"], sentence: "路滑小心。", breakdown: ["艸", "台"], logic: "層疊台貌之草。", story: "下過大雨，小溪邊的牆角長出了綠苔。" },
    "蔬": { grade: "2A", zhuyin: "ㄕㄨ", comp: "grass", definition: "食草。", phrases: ["蔬果"], sentence: "多吃水果蔬菜。", breakdown: ["艸", "疏"], logic: "暢通腸胃。之源。", story: "我们要養成愛吃蔬菜果實的好習慣喔。" },
    "荷": { grade: "2B", zhuyin: "ㄏㄜˊ", comp: "grass", definition: "蓮；承。", phrases: ["荷花"], sentence: "荷葉很大。", breakdown: ["艸", "何"], logic: "承重之力。", story: "微風吹過，池中荷葉像在那裡點點頭。" },
    "藥": { grade: "2B", zhuyin: "ㄧㄠˋ", comp: "grass", definition: "醫治藥。", phrases: ["吃藥"], sentence: "感冒吃藥。", breakdown: ["艸", "樂"], logic: "使人康樂之草。", story: "良藥苦口利於病，大家生病不要躲避它。" },

    // 11. 糸部 (7 個)
    "綠": { grade: "1B", zhuyin: "ㄌㄩˋ", comp: "silk", definition: "色名。", phrases: ["綠色"], sentence: "綠草茵茵。", breakdown: ["糹", "彔"], logic: "絲線之木綠色。", story: "草地綠意盎然，看著令人心曠神怡。" },
    "紅": { grade: "1B", zhuyin: "ㄏㄨㄥˊ", comp: "silk", definition: "色名。", phrases: ["紅色"], sentence: "臉通紅。", breakdown: ["糹", "工"], logic: "工匠染成之赤。", story: "太陽公公有一張紅通通的大臉盤。" },
    "給": { grade: "1B", zhuyin: "ㄍㄟˇ", comp: "silk", definition: "付與。", phrases: ["送給"], sentence: "拿給他看。", breakdown: ["糹", "合"], logic: "如線合流交予。", story: "謝謝你給我這個這麼好的學習機會。" },
    "緊": { grade: "2A", zhuyin: "ㄐㄧㄣˇ", comp: "silk", definition: "牢固。", phrases: ["緊身"], sentence: "別害怕。", breakdown: ["糹", "臤"], logic: "韌線之堅臣。", story: "比賽快開始了，選手們都感到很緊湊。" },
    "線": { grade: "2A", zhuyin: "ㄒㄧㄢˋ", comp: "silk", definition: "細長條。", phrases: ["毛線"], sentence: "畫直線。", breakdown: ["糹", "泉"], logic: "絲泉如注。", story: "媽媽正在一針一線地幫我縫補破洞。" },
    "絲": { grade: "2B", zhuyin: "ㄙ", comp: "silk", definition: "幼蠶絲。", phrases: ["絲線"], sentence: "摸手柔軟。", breakdown: ["絲"], logic: "象形二絲。", story: "白白的蠶寶寶正在大口吃著桑葉吐絲。" },
    "終": { grade: "2B", zhuyin: "ㄓㄨㄥ", comp: "silk", definition: "完結。", phrases: ["終點"], sentence: "終於完成。", breakdown: ["糹", "冬"], logic: "冬季結案。", story: "經過長途跋涉，我們這才抵達終點站。" },

    // 12. 虫部 (10 個)
    "蛙": { grade: "2A", zhuyin: "ㄨㄚ", comp: "insect", definition: "青蛙。", phrases: ["青蛙"], sentence: "跳跳跳。", breakdown: ["虫", "圭"], logic: "田蛙之聲。", story: "池塘邊住著幾隻大口吃害蟲的青蛙。" },
    "螃": { grade: "2A", zhuyin: "ㄆㄤˊ", comp: "insect", definition: "螃蟹。", phrases: ["螃蟹"], sentence: "横著走。", breakdown: ["虫", "旁"], logic: "側行之虫。", story: "螃蟹揮動著兩隻大螯，看起來真威風。" },
    "蟹": { grade: "2A", zhuyin: "ㄒㄧㄝˋ", comp: "insect", definition: "螃蟹。", phrases: ["螃蟹"], sentence: "螃蟹在海。", breakdown: ["角", "刀", "牛", "虫"], logic: "解開硬殼之虫。", story: "小溪裡發現幾隻正在吐泡泡的小蟹。" },
    "蝦": { grade: "2A", zhuyin: "ㄒㄧㄚ", comp: "insect", definition: "水族。", phrases: ["蝦子"], sentence: "蝦仁飯。", breakdown: ["虫", "叚"], logic: "隱蔽假色虫。", story: "紅色的小蝦在水箱裡自在地游來游去。" },
    "蚯": { grade: "2B", zhuyin: "ㄑㄧㄡ", comp: "insect", definition: "地龍。", phrases: ["蚯蚓"], sentence: "土裡鑽。", breakdown: ["虫", "丘"], logic: "丘陵地龍。", story: "蚯蚓會幫泥土鬆土，是農夫的好幫手。" },
    "蚓": { grade: "2B", zhuyin: "ㄧㄣˇ", comp: "insect", definition: "地龍。", phrases: ["蚯蚓"], sentence: "伸縮爬。", breakdown: ["虫", "引"], logic: "引導行進之肢。", story: "蚯蚓雖然沒有眼睛，但他很會鑽洞穴。" },
    "蝌": { grade: "2B", zhuyin: "ㄎㄜ", comp: "insect", definition: "蛙子。", phrases: ["蝌蚪"], sentence: "池子游泳。", breakdown: ["虫", "科"], logic: "禾實般粒之虫。", story: "小蝌蚪長大後，尾巴會慢慢消失喔。" },
    "蚪": { grade: "2B", zhuyin: "ㄉㄡˇ", comp: "insect", definition: "蛙子。", phrases: ["蝌蚪"], sentence: "找媽媽。", breakdown: ["虫", "斗"], logic: "如勺（斗）之虫。", story: "小蝌蚪在水草間愉快地游著找媽媽。" },
    "蜘": { grade: "2B", zhuyin: "ㄓ", comp: "insect", definition: "結網虫。", phrases: ["蜘蛛"], sentence: "在牆角。", breakdown: ["虫", "知"], logic: "知曉結網之虫。", story: "蜘蛛結網很有耐性，一絲一毫都不亂。" },
    "蛛": { grade: "2B", zhuyin: "ㄓㄨ", comp: "insect", definition: "結網虫。", phrases: ["蜘蛛"], sentence: "在結網。", breakdown: ["虫", "朱"], logic: "如珠寶粒虫。", story: "這隻蜘蛛長得很大，正等著昆蟲上鉤。" },

    // 13. 日部 (10 個)
    "星": { grade: "1A", zhuyin: "ㄒㄧㄥ", comp: "sun", definition: "星體。", phrases: ["星星"], sentence: "星星在閃耀。", breakdown: ["日", "生"], logic: "日生之光感。", story: "我想摘下一顆明亮的星星送給媽媽。" },
    "早": { grade: "1A", zhuyin: "ㄗㄠˇ", comp: "sun", definition: "清晨。", phrases: ["早安"], sentence: "要吃早餐。", breakdown: ["日", "十"], logic: "日照頭頂（十）。", story: "早起的鳥兒有蟲吃，大家要早點起床。" },
    "時": { grade: "1B", zhuyin: "ㄕˊ", comp: "sun", definition: "時程。", phrases: ["時間"], sentence: "守時。", breakdown: ["日", "寺"], logic: "日測光段。", story: "時間一分一秒地過去，我們要珍惜它。" },
    "陽": { grade: "1B", zhuyin: "ㄧㄤˊ", comp: "sun", definition: "太陽。", phrases: ["陽光"], sentence: "曬曬太陽。", breakdown: ["阝", "昜"], logic: "山頭之光。", story: "太陽公公出來了，今天又是個出遊天。" },
    "候": { grade: "2A", zhuyin: "ㄏㄡˋ", comp: "sun", definition: "時節等待。", phrases: ["等候"], sentence: "什麼時候要出發？", breakdown: ["亻", "侯"], logic: "人射標靶待訊。", story: "等候公車需要耐心，不要在路邊玩耍。" },
    "晴": { grade: "2A", zhuyin: "ㄑㄧㄥˊ", comp: "sun", definition: "晴天。", phrases: ["晴朗"], sentence: "太陽出來了。", breakdown: ["日", "青"], logic: "日出而天青。", story: "晴天的時候出門踏青，心情最舒暢了。" },
    "晚": { grade: "2A", zhuyin: "ㄨㄢˇ", comp: "sun", definition: "夜間。", phrases: ["晚上"], sentence: "要睡覺了。", breakdown: ["日", "免"], logic: "日消（免）逝也。", story: "晚上睡覺前，別忘了跟爸爸說晚安。" },
    "暗": { grade: "2A", zhuyin: "ㄢˋ", comp: "sun", definition: "無光。", phrases: ["黑暗"], sentence: "不開燈好暗。", breakdown: ["日", "音"], logic: "日隱之影感。", story: "夜深了，外面的街道變得黑暗寂靜。" },
    "昨": { grade: "2B", zhuyin: "ㄗㄨㄛˊ", comp: "sun", definition: "前日。", phrases: ["昨天"], sentence: "昨天是週假。", breakdown: ["日", "乍"], logic: "日忽過後（乍）。", story: "昨天發生過的美好回憶，我都記在內心。" },
    "晨": { grade: "2B", zhuyin: "ㄔㄣˊ", comp: "sun", definition: "清早。", phrases: ["晨跑"], sentence: "早晨好美。", breakdown: ["日", "辰"], logic: "日甦於辰（晨）。", story: "公雞喔喔叫，叫醒了正在熟睡的晨曦。" },

    // 14. 門部 (6 個)
    "問": { grade: "1A", zhuyin: "ㄨㄣˋ", comp: "gate", definition: "請教。", phrases: ["問題"], sentence: "有事可以問我。", breakdown: ["門", "口"], logic: "門口打聽。", story: "不懂的事情開口問一問，煩惱就消了。" },
    "間": { grade: "1A", zhuyin: "ㄐㄧㄢ", comp: "gate", definition: "房區；隙。", phrases: ["中間"], sentence: "房間大大的。", breakdown: ["門", "日"], logic: "門縫見日。", story: "這兩個大樹之間，停了一隻漂亮蝴蝶。" },
    "閃": { grade: "2A", zhuyin: "ㄕㄢˇ", comp: "gate", definition: "避；亮。", phrases: ["閃亮"], sentence: "打雷閃電。", breakdown: ["門", "人"], logic: "門側避人。", story: "黑夜的星星正對著我們閃爍眨眼睛。" },
    "門": { grade: "2A", zhuyin: "ㄇㄣˊ", comp: "gate", definition: "建築口。", phrases: ["開門"], sentence: "把門關上。", breakdown: ["門"], logic: "象形門扉。", story: "推進這扇大門，就有精彩的探險等著你。" },
    "閒": { grade: "2A", zhuyin: "ㄒㄧㄢˊ", comp: "gate", definition: "安靜暇。", phrases: ["悠閒"], sentence: "我很愛悠閒看書。", breakdown: ["門", "月"], logic: "靜夜窺月。", story: "安靜的客廳裡，爸爸正在悠閒地看報。" },
    "闖": { grade: "2A", zhuyin: "ㄔㄨㄤˇ", comp: "gate", definition: "猛衝過路。", phrases: ["闖紅燈"], sentence: "不要闖禍。", breakdown: ["門", "馬"], logic: "馬破門出。", story: "小馬快速地往圍欄外闖，奔向大草原。" },

    // 15. 雨部 (5 個)
    "雨": { grade: "1B", zhuyin: "ㄩˇ", comp: "rain", definition: "雲降水珠。", phrases: ["下雨"], sentence: "外面很大雨。", breakdown: ["雨"], logic: "象形雲聚落水。", story: "大雨過後，空氣變得涼爽又清新迷人。" },
    "雲": { grade: "2A", zhuyin: "ㄩㄣˊ", comp: "rain", definition: "水蒸氣團。", phrases: ["白雲"], sentence: "看看雲朵。", breakdown: ["雨", "云"], logic: "天雨聚如云團旋。", story: "抬頭看看雲海，變化多端真是有趣極了。" },
    "電": { grade: "2A", zhuyin: "ㄉㄧㄢˋ", comp: "rain", definition: "自然閃光；磁力。", phrases: ["電視"], sentence: "節約用電。", breakdown: ["雨", "申"], logic: "雨中伸展強能軌。", story: "電視機會用到電力，我們要節約能源喔。" },
    "雪": { grade: "2B", zhuyin: "ㄒㄩㄝˇ", comp: "rain", definition: "白色冰晶片。", phrases: ["雪人"], sentence: "下雪了。", breakdown: ["雨", "彐"], logic: "雨水（雨）在手巾處（彐）結成。", story: "我們去高山上滾雪球、堆一個大雪人。" },
    "露": { grade: "2B", zhuyin: "ㄌㄨˋ", comp: "rain", definition: "凝聚水珠；現。", phrases: ["露水"], sentence: "露天劇場。", breakdown: ["雨", "路"], logic: "雨在大道後凝結之餘。", story: "別讓你的壞脾氣在大眾面前流露出來喔。" },

    // 16. 鳥/隹部 (7 個)
    "雀": { grade: "1B", zhuyin: "ㄑㄩㄝˋ", comp: "bird", definition: "巧羽類家鳥。", phrases: ["麻雀"], sentence: "小鳥跳跳跳。", breakdown: ["小", "隹"], logic: "指體型微小的鳥。", story: "森林裡的孔雀展開羽毛，色彩鮮豔奪目。" },
    "雙": { grade: "1B", zhuyin: "ㄕㄨㄤ", comp: "bird", definition: "一對。", phrases: ["雙手"], sentence: "這一對鞋子。", breakdown: ["隹", "隹", "又"], logic: "手抓二鳥而合對。", story: "成雙成對的小蝴蝶，在花叢跳舞玩耍。" },
    "隻": { grade: "2A", zhuyin: "ㄓ", comp: "bird", definition: "單粒。", phrases: ["一隻小鳥"], sentence: "這只是個例句。", breakdown: ["隹", "又"], logic: "手抓一鳥而獨個。", story: "那隻黑亮的小狗正對著我們搖尾巴呢。" },
    "雞": { grade: "2B", zhuyin: "ㄐㄧ", comp: "bird", definition: "家禽鳥類的一種。", phrases: ["母雞"], sentence: "吃雞排。", breakdown: ["奚", "隹"], logic: "人役之鳥。", story: "母雞媽媽帶著一群小雞去草地抓蟲吃。" },
    "鴨": { grade: "2B", zhuyin: "ㄧㄚ", comp: "bird", definition: "水禽。", phrases: ["鴨子"], sentence: "小鴨游泳。", breakdown: ["甲", "鳥"], logic: "鳥聲如甲。", story: "池塘裡有一群可愛的黃色小鴨子。" },
    "鵝": { grade: "2B", zhuyin: "ㄜˊ", comp: "bird", definition: "大型水族鳥。", phrases: ["天鵝"], sentence: "白雪般的鵝。", breakdown: ["我", "鳥"], logic: "似我身量大之鳥。", story: "這隻白色的鵝伸長脖子，大聲嘎嘎叫。" },
    "鴿": { grade: "2B", zhuyin: "ㄍㄜ", comp: "bird", definition: "和平之禽。", phrases: ["鴿子"], sentence: "白鴿飛舞。", breakdown: ["合", "鳥"], logic: "集合之鳥也。", story: "信鴿可以幫古人傳信，是個得力小幫手。" }
  }
};

const fileContent = 'const libraryData = ' + JSON.stringify(rawData, null, 2) + ';\n\nconst defaultUsers = [\n  { id: \'admin\', name: \'大師老師\', role: \'teacher\', password: \'123\' }\n];\n';

fs.writeFileSync('C:/Users/yiwen/.gemini/antigravity/scratch/data.js', fileContent);
console.log('data.js successfully generated.');
